module.exports={
    PRODUCT_COLLECTION:'products',
    USER_COLLECTION:'users',
    CART_COLLECTION:'carts',
    ORDER_COLLECTION:'orders',
    ADMIN_COLLECTION:'admins',
    PRODUCTS_CATEGORY_COLLECTION:'products-category',
    OFFER_COLLECTION:'offers'
}